---
  - name: Playbook con Debug y Condiciones
    hosts: all
    gather_facts: no

    vars:
      estado_servidor: "activo"

    tasks:
      - name: Verificar estado del servidor
        debug:
          msg: "El servidor está en funcionamiento."
        when: estado_servidor == "activo"

      - name: Mostrar advertencia si el servidor está inactivo
        debug:
          msg: "Advertencia: El servidor está inactivo."
        when: estado_servidor != "activo"
